-- Backfill per-option rationale (rationaleJson) for seed objective questions.
-- Safe to run after import-objective-tests.sql; only updates rows whose prompt matches.
-- rationaleJson is a JSON array aligned by index to optionsJson ("" means no specific reason).

-- Management/operational bank (C1/C2/C3/E1/F1)
UPDATE `objectiveQuestions` SET `rationaleJson` = '["A fixed cost stays constant in total over the relevant range, so the cost per unit falls as activity rises, and it varies per unit while remaining constant in total.","A step cost remains constant within a range then jumps to a new level; it does not vary smoothly per unit.","A variable cost varies in total with activity but is constant per unit, the opposite of the description.","A semi-variable cost has both a fixed and a variable element."]' WHERE `prompt` = 'A cost that remains constant in total within a relevant range of activity but varies per unit as activity changes is known as:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Direct materials become part of inventory as a product cost.","Direct labour is a product cost capitalised into inventory.","Administrative salaries are incurred for the period and expensed immediately, so they are a period cost.","Factory rent is a production overhead absorbed into inventory as a product cost."]' WHERE `prompt` = 'Which cost is classified as a period cost rather than a product cost?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Direct material varies directly with the level of production output, so it is a variable cost.","Straight-line depreciation is fixed in total regardless of output unless it is based on units of production.","Machine rental on a fixed lease is a fixed cost; it does not change with activity levels.","Sales commission per unit is paid per unit sold and therefore varies with activity, making it a variable cost.","Annual insurance premium is a fixed cost for the period."]' WHERE `prompt` = 'Which two of the following are examples of variable costs?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["This is marginal costing treatment, not absorption costing.","Fixed production overheads are not simply expensed in the period under absorption costing.","Absorption costing uses an overhead absorption rate to charge fixed production overheads to units of output so they are included in inventory valuation.","Fixed production overheads are absorbed into inventory, not ignored."]' WHERE `prompt` = 'Under absorption costing, fixed production overheads are:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Marginal costing is not used for external financial reporting.","Marginal costing assigns only variable costs to products and avoids arbitrary fixed-overhead apportionment, aiding short-term decisions.","Marginal costing does not value inventory at full production cost.","Marginal costing excludes fixed overheads from product cost."]' WHERE `prompt` = 'The main advantage of marginal costing relative to absorption costing is that it:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Full production cost includes fixed overheads; that is not how contribution is derived.","Contribution equals sales revenue less total variable costs, the amount that covers fixed costs and profit.","Fixed costs are deducted after contribution to reach profit.","This describes a wider deduction than contribution requires."]' WHERE `prompt` = 'In a marginal costing income statement, contribution is calculated as:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The income statement reports performance over a period.","The cash flow statement covers a period of cash movements.","The statement of financial position reports assets, liabilities and equity at a specific point in time.","The statement of changes in equity covers a period."]' WHERE `prompt` = 'Which financial statement reports a company''s financial position at a point in time?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Cash receipt is the cash basis, not the accruals basis.","Accruals basis recognises revenue when it is earned, that is when goods are delivered or services performed, regardless of cash timing.","Sending an invoice is not the point of recognition under accruals.","Payment of goods is the cash basis of recognition."]' WHERE `prompt` = 'Under the accruals (matching) basis of accounting, revenue is recognised when:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A loan due in five years is a non-current liability.","Inventory held for resale is expected to be converted to cash within the operating cycle, so it is a current asset.","Equipment used in operations is a non-current (tangible) asset.","Share capital is equity, not an asset."]' WHERE `prompt` = 'Which of the following would appear as a current asset?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The margin of safety is not defined as contribution over profit.","This describes the contribution margin, not the margin of safety.","Fixed costs divided by C/S ratio gives break-even revenue.","Sales less variable costs is contribution."]' WHERE `prompt` = 'The margin of safety is:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["R48,000 would be a figure much lower than required.","Break-even revenue = fixed costs / C/S ratio = 120,000 / 0.40 = R300,000.","R200,000 is not consistent with the given ratio and fixed costs.","R480,000 is higher than the correct break-even revenue."]' WHERE `prompt` = 'If the contribution/sales (C/S) ratio is 40% and fixed costs are R120,000, the break-even revenue (in rand) is:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Supplier bargaining power is an industry-level (Porter five forces) factor.","Interest rates are part of the economic macro-environment assessed in a PESTEL analysis.","Customer loyalty is firm-level.","Internal staff morale is an internal factor."]' WHERE `prompt` = 'Which of the following is a macro-environmental factor in a PESTEL analysis?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A matrix structure combines functional and project dimensions.","A divisional structure groups by product, geography or customer.","A functional structure groups employees by specialist function such as marketing, finance and production.","A flat structure has few management layers, not functional groupings."]' WHERE `prompt` = 'Which structure groups employees by specialist function such as marketing, finance and production?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Maximising short-term share price is not the purpose of governance.","Corporate governance is the system by which companies are directed and controlled, providing accountability to stakeholders.","Governance does not eliminate all business risk.","Governance does not guarantee dividends."]' WHERE `prompt` = 'The main purpose of corporate governance is to:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A brand name is an identifiable non-physical asset, an intangible asset.","Delivery vehicles are tangible non-current assets.","A computer software licence is a non-physical, identifiable asset, so an intangible asset.","Raw materials inventory is a current (tangible) asset.","Cash at bank is a current (financial) asset, not an intangible."]' WHERE `prompt` = 'Which two of the following are examples of intangible assets?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Suppliers are exposed through trade credit but less directly than long-term lenders.","Lenders have lent long-term money and are therefore directly concerned with the entity''s financial stability and going concern.","Competitors are not financially exposed to the entity.","The general public has only a general interest."]' WHERE `prompt` = 'Which stakeholder group is most directly concerned with the going concern of a business because they have lent it long-term money?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["FIFO assumes earliest goods are sold first, leaving the most recently purchased goods in closing inventory at their more recent prices.","The oldest purchase prices relate to costs of goods sold under FIFO, not closing inventory.","Average purchase price relates to the weighted-average method.","The lowest purchase price is not a FIFO concept."]' WHERE `prompt` = 'Under FIFO, the cost of closing inventory is based on:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["EOQ balances ordering (set-up) costs against inventory holding (carrying) costs.","Fixed versus variable costs is not the EOQ trade-off.","Direct versus indirect costs is a classification issue, not EOQ.","Budgeted versus actual costs is a variance concept."]' WHERE `prompt` = 'The economic order quantity (EOQ) model balances:';

-- Management bank (P2/E2/F2)
UPDATE `objectiveQuestions` SET `rationaleJson` = '["A top-down budget is imposed by senior management.","A bottom-up (participative) budget is built from the input of lower-level managers and consolidated upwards.","A zero-based budget starts from a zero base each period.","A rolling budget is continually updated on a rolling basis."]' WHERE `prompt` = 'A budget prepared by each manager and consolidated upwards is best described as a:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Budgetary slack is deliberately understating revenue or overstating costs to make targets easier to achieve.","The difference between fixed and variable costs is a cost behaviour concept.","A cash cushion for emergencies is not budgetary slack.","The variance between budget and actual is a performance measure."]' WHERE `prompt` = 'Budgetary slack refers to:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A cash budget records cash inflows and outflows when cash moves.","Depreciation is non-cash and appears only in the profit statement.","Cash budgets do include payments to suppliers.","Cash budgets may cover multiple periods."]' WHERE `prompt` = 'The cash budget differs from the profit statement primarily because it:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Participative budgeting improves ownership and commitment among managers.","It does not automatically reduce slack and can increase it.","It incorporates the honest, local knowledge of operating managers.","Budgeting still requires periodic review."]' WHERE `prompt` = 'Which two of the following are benefits of participative budgeting?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Asset turnover = revenue / capital employed, measuring the efficiency of asset use in generating sales.","Current ratio is a liquidity measure.","Gross profit margin measures profitability, not asset use.","Gearing measures the debt/equity mix."]' WHERE `prompt` = 'Which ratio measures how effectively a business is using its non-current assets to generate revenue?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The balanced scorecard combines financial, customer, internal business process, and learning and growth perspectives.","Suppliers, competitors and regulators are not scorecard perspectives.","Profit, cash and liquidity are financial measures only.","Cost, quality and time are operational trade-offs, not scorecard perspectives."]' WHERE `prompt` = 'A balanced scorecard emphasises financial measures together with which three other perspectives?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A favourable material price variance means the actual purchase price was below the standard price.","Using more material than standard causes an adverse usage variance.","Higher material waste is an adverse usage issue.","The purchase price exceeding standard would be an adverse price variance."]' WHERE `prompt` = 'A favourable material price variance indicates that:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Projects move through initiation, planning, execution, and closure.","Closure is the final stage, not the second.","Execution follows planning, so this order is wrong.","Planning comes before execution, so this order is wrong."]' WHERE `prompt` = 'Which of the following is the correct order of the generic project lifecycle stages?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The critical path is the sequence of dependent activities with the longest total duration, determining the minimum project time.","The path with the least cost is not the critical path.","The shortest duration path is not critical.","Any path without float is a description of critical path activities, but the correct definition is the longest total duration."]' WHERE `prompt` = 'In a project network diagram, the critical path is:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Total float is the time an activity can be delayed before delaying project completion.","The buffer between actual and budgeted cost is a cost contingency, not float.","Extra time on the critical path is not how float is defined.","Optimistic/pessimistic estimates relate to three-point estimation, not float."]' WHERE `prompt` = 'A project''s total float (slack) is best described as:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Unrealistic initial estimates are a common cause of time and cost overruns.","Poor scope control allows scope creep, a common cause of overruns.","Excessively detailed documentation is not a typical cause of overruns.","Generous contingency reserves reduce overrun risk rather than cause it."]' WHERE `prompt` = 'Which two of the following are common causes of project overruns?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The project charter formally authorises the project and defines its scope and objectives.","Recording lessons learned happens at closure.","Tracking day-to-day progress is a control activity, not the charter''s purpose.","Setting the marketing budget is unrelated to the charter."]' WHERE `prompt` = 'The project charter is primarily used to:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A declared dividend is a distribution owed to shareholders, not an asset.","A declared but unpaid dividend is a current liability payable until settled.","It is not equity until it is recognised in retained earnings/equity for the next period.","It is a known obligation, not a contingent liability."]' WHERE `prompt` = 'A dividend declared but not yet paid should be classified in the statement of financial position as:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The parent''s investment is not shown as a non-current asset on consolidation.","On consolidation the parent''s investment is eliminated against the subsidiary''s equity to avoid double counting.","It is recorded at cost, not re-measured to market value each year.","It is replaced by the subsidiary''s net assets, not merely disclosed in the notes."]' WHERE `prompt` = 'In a consolidated statement of financial position, the parent''s investment in the subsidiary is:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["A provision requires a present obligation from a past event, a probable outflow and a reliably estimable amount.","A future expected loss is not yet a present obligation.","A customer order creates revenue, not a provision.","Management intent to donate is not a present obligation from a past event."]' WHERE `prompt` = 'A provision is recognised when:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Going concern assumes the entity will continue operating for the foreseeable future, so assets are not valued at forced-sale values.","Liquidation soon would contradict going concern.","Assets are not always recorded at market value under going concern.","Not all liabilities must be settled immediately."]' WHERE `prompt` = 'The going concern assumption means that:';

-- Strategic bank (E3/P3/F3)
UPDATE `objectiveQuestions` SET `rationaleJson` = '["Cost leadership is one of Porter''s three generic competitive strategies.","Market skimming is a pricing tactic, not a generic strategy.","Conglomerate integration is a growth/diversification strategy.","Backward diversification is not a Porter generic strategy."]' WHERE `prompt` = 'According to Porter, which of the following is a generic competitive strategy?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Ansoff''s matrix categorises strategies along new/existing products and new/existing markets.","Cost and price are not the Ansoff dimensions.","Strengths and weaknesses belong to SWOT.","Supply and demand are not the Ansoff axes."]' WHERE `prompt` = 'Ansoff''s matrix categorises growth strategies along which two dimensions?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["SWOT stands for Strengths, Weaknesses, Opportunities and Threats.","Sales, wages, overheads and tax are not the SWOT components.","Risks, returns, rewards and regulation are not SWOT.","Suppliers, workers, owners and trade are stakeholders, not SWOT."]' WHERE `prompt` = 'A SWOT analysis examines a company''s:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Entering an unfamiliar market with limited experience is a diversification risk.","Diversification can dilute focus on the current core business.","Diversification does not guarantee higher returns.","It does not eliminate competitive rivalry."]' WHERE `prompt` = 'Which two of the following are examples of diversification risks or challenges a company may face?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Corporate strategy concerns the overall scope and direction of the organisation and how resources are deployed across business units.","Assigning employees to roles is an operational matter.","Pricing a single product is operational.","Choosing a supplier is operational."]' WHERE `prompt` = 'Corporate strategy answers the question:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Risk mitigation reduces the likelihood or impact of a risk.","Acceptance retains the risk without action.","Avoidance eliminates the risk.","Transfer shifts the risk to another party."]' WHERE `prompt` = 'Which response involves taking action to reduce the likelihood or impact of a risk?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Insurance shifts the financial consequence of a risk to a third party, i.e. risk transfer.","Avoidance would eliminate the activity causing the risk.","Acceptance retains the risk.","Retention is the same as acceptance."]' WHERE `prompt` = 'Purchasing an insurance policy is an example of which risk treatment?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["High-likelihood, high-impact risks fall in the high-priority band and require urgent mitigation.","Low-priority zone is for low-likelihood, low-impact risks.","Residual risk is what remains after mitigation.","Opportunity zone is not how a standard risk map classifies high-impact, high-likelihood risk."]' WHERE `prompt` = 'A risk with high impact and high likelihood would normally be placed in which zone of a risk map?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Beta measures a share''s systematic risk, i.e. its sensitivity to overall market movements relative to the market.","Beta captures systematic risk, not only idiosyncratic risk.","Liquidity risk is not what beta measures.","Interest rate risk is a component of systematic risk but not all that beta captures."]' WHERE `prompt` = 'The beta of a company''s shares is a measure of:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Interest rate movements are a financial/market risk.","Currency (exchange rate) fluctuations are a financial/market risk.","A key employee resigning is an operational risk.","Storm damage to a factory is a physical/hazard risk."]' WHERE `prompt` = 'Which two of the following are examples of financial (market) risks?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Retained earnings avoid issue/floatation costs and do not dilute existing shareholdings.","Retained earnings are not risk-free.","They do not drive the WACC to zero.","They still involve reinvesting profit rather than distributing it."]' WHERE `prompt` = 'The theoretical advantage of raising finance through retained earnings over a new share issue is that:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["NPV discounts all future cash flows, recognising the time value of money across the entire project life.","Payback is simpler to calculate, which is a weakness of NPV.","NPV does not ignore the cost of capital; it uses it as the discount rate.","NPV uses cash flows, not accounting profit."]' WHERE `prompt` = 'Net present value (NPV) is preferred to payback period as an investment appraisal method primarily because it:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["The IRR is the discount rate at which the net present value of a project equals zero.","Payback period is a different measure.","Accounting profit equals cash flow only under specific assumptions.","IRR is not about maximising the cost of capital."]' WHERE `prompt` = 'The internal rate of return (IRR) is the discount rate at which:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["WACC is the blended cost of a company''s debt and equity financing, weighted by their proportions in the capital structure.","The marginal tax rate is a component, not the WACC itself.","The return on the market portfolio is not the WACC.","Dividend per share is an equity return measure, not the WACC."]' WHERE `prompt` = 'Which of the following best describes the weighted average cost of capital (WACC)?';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Merger value to shareholders is best reflected in the present value of expected synergies and incremental cash flows.","The number of new board members is not a value measure.","Historic share price alone does not measure merger value.","Brand advertising value is not the measure of shareholder value created."]' WHERE `prompt` = 'When assessing a merger, the value created for shareholders is usually measured by:';

UPDATE `objectiveQuestions` SET `rationaleJson` = '["Debt is typically the cheapest source of finance because interest is tax-deductible and lenders face lower risk (priority repayment) than shareholders.","Ordinary shares are riskier and carry a higher required return.","Preference shares rank above ordinary shares but below debt in safety.","Retained earnings carry an opportunity cost higher than cheap debt."]' WHERE `prompt` = 'Which financing source generally carries the lowest required rate of return for a company because it is repaid before shareholders?';
